version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
  post_build:
    commands:
      - aws deploy push --application-name spring-boot-web --s3-location s3://ktakasak-artifact/spring-boot-web-artifact.zip --source target
artifacts:
  files:
    - '*/spring-boot-web-0.0.1-SNAPSHOT.jar'
  base-directory: target
  discard-paths: yes